### ISSUE TITLE
code about Pre-model prompting

### ISSUE THREAD

**Issue by Ahnsun** [raoyongming/DenseCLIP#11]
Hi, the paper proposed two context prompting methods which are pre-model and post-model prompting respectively。 But I only find the post-model methed from the source code. Could you please provide the pre-model's code? That will help understand a lot. Thanks!

**Comment by raoyongming** [comment]
Since post-model prompting is much more efficient and effective than pre-model prompting, we use the post-model strategy as the default setting in our final models. Since it is a bit difficult to make the code compatible with both two versions, I can send you our original implementation privately. Could please you give me your email address?

**Comment by Ahnsun** [comment]
Sure，yuen@hust.edu.cn
