### ISSUE TITLE
Questions about the architecture

### ISSUE THREAD

**Issue by xiaoachen98** [raoyongming/DenseCLIP#21]
You present in the paper only the results related to Semantic FPN.

Have you conducted any relevant experiments based on dilated backbone methods (e.g. DeepLabV3+)?

Is the reason for not using dilated backbone-based methods that you are looking for fewer FLOPs or have you found that the results are not good?

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We didn't test dilated backbones because we want to keep the pre-trained CLIP backbones unchanged. Since our method largely relies on the pre-trained correlation between visual and text embeddings, modifying the backbone to a dilated version may make the initial pixel-text score maps inaccurate.

**Comment by xiaoachen98** [comment]
Thanks for your quick reply! I will try the effect of using dilated backbone.
