### ISSUE TITLE
some question about pixel-text matching loss

### ISSUE THREAD

**Issue by Yu-zhengbo** [raoyongming/DenseCLIP#53]
In the paper, I did't find the description about the pixel-text matching loss. Then I try to find the loss in the open source code, but I fall. In the follow picture, the self.with_identity_head and self.with_auxiliary_head are None, so I just can find the task loss. Please help me. Thank you.
![image](https://github.com/raoyongming/DenseCLIP/assets/72426381/c0393550-4aa9-4a51-8e8e-46d13bcffc26)

**Comment by raoyongming** [comment]
Hi, the pixel-text matching loss is computed using `identity head` since it already is a classification map and doesn't require a linear classifier head. The head is not `None` (see [here](https://github.com/raoyongming/DenseCLIP/blob/5eda47f01a1011286c98425554cc96e7df6eb759/segmentation/configs/_base_/models/denseclip_r50.py#L43)).
